<template>
  <div class="typeColumn" :style="{fontFamily: typeface}">
    <h2 class="typeface">
        {{ typeface }}
    </h2>
    <div class="charmap" :style="fullStyles">
        <div>&nbsp;</div>
        <div>!</div>
        <div>"</div>
        <div>#</div>
        <div>$</div>
        <div>%</div>
        <div>&amp;</div>
        <div>'</div>
        <div>(</div>
        <div>)</div>
        <div>*</div>
        <div>+</div>
        <div>,</div>
        <div>-</div>
        <div>.</div>
        <div>/</div>
        <div>0</div>
        <div>1</div>
        <div>2</div>
        <div>3</div>
        <div>4</div>
        <div>5</div>
        <div>6</div>
        <div>7</div>
        <div>8</div>
        <div>9</div>
        <div>:</div>
        <div>;</div>
        <div>&lt;</div>
        <div>=</div>
        <div>&gt;</div>
        <div>?</div>
        <div>@</div>
        <div>A</div>
        <div>B</div>
        <div>C</div>
        <div>D</div>
        <div>E</div>
        <div>F</div>
        <div>G</div>
        <div>H</div>
        <div>I</div>
        <div>J</div>
        <div>K</div>
        <div>L</div>
        <div>M</div>
        <div>N</div>
        <div>O</div>
        <div>P</div>
        <div>Q</div>
        <div>R</div>
        <div>S</div>
        <div>T</div>
        <div>U</div>
        <div>V</div>
        <div>W</div>
        <div>X</div>
        <div>Y</div>
        <div>Z</div>
        <div>[</div>
        <div>\</div>
        <div>]</div>
        <div>^</div>
        <div>_</div>
        <div>`</div>
        <div>a</div>
        <div>b</div>
        <div>c</div>
        <div>d</div>
        <div>e</div>
        <div>f</div>
        <div>g</div>
        <div>h</div>
        <div>i</div>
        <div>j</div>
        <div>k</div>
        <div>l</div>
        <div>m</div>
        <div>n</div>
        <div>o</div>
        <div>p</div>
        <div>q</div>
        <div>r</div>
        <div>s</div>
        <div>t</div>
        <div>u</div>
        <div>v</div>
        <div>w</div>
        <div>x</div>
        <div>y</div>
        <div>z</div>
        <div>{</div>
        <div>|</div>
        <div>}</div>
        <div>~</div>
        <div>¡</div>
        <div>¢</div>
        <div>£</div>
        <div>¤</div>
        <div>¥</div>
        <div>¦</div>
        <div>§</div>
        <div>¨</div>
        <div>©</div>
        <div>ª</div>
        <div>«</div>
        <div>¬</div>
        <div>-</div>
        <div>®</div>
        <div>¯</div>
        <div>°</div>
        <div>±</div>
        <div>²</div>
        <div>³</div>
        <div>´</div>
        <div>µ</div>
        <div>¶</div>
        <div>·</div>
        <div>¸</div>
        <div>¹</div>
        <div>º</div>
        <div>»</div>
        <div>¼</div>
        <div>½</div>
        <div>¾</div>
        <div>¿</div>
        <div>À</div>
        <div>Á</div>
        <div>Â</div>
        <div>Ã</div>
        <div>Ä</div>
        <div>Å</div>
        <div>Æ</div>
        <div>Ç</div>
        <div>È</div>
        <div>É</div>
        <div>Ê</div>
        <div>Ë</div>
        <div>Ì</div>
        <div>Í</div>
        <div>Î</div>
        <div>Ï</div>
        <div>Ð</div>
        <div>Ñ</div>
        <div>Ò</div>
        <div>Ó</div>
        <div>Ô</div>
        <div>Õ</div>
        <div>Ö</div>
        <div>×</div>
        <div>Ø</div>
        <div>Ù</div>
        <div>Ú</div>
        <div>Û</div>
        <div>Ü</div>
        <div>Ý</div>
        <div>Þ</div>
        <div>ß</div>
        <div>à</div>
        <div>á</div>
        <div>â</div>
        <div>ã</div>
        <div>ä</div>
        <div>å</div>
        <div>æ</div>
        <div>ç</div>
        <div>è</div>
        <div>é</div>
        <div>ê</div>
        <div>ë</div>
        <div>ì</div>
        <div>í</div>
        <div>î</div>
        <div>ï</div>
        <div>ð</div>
        <div>ñ</div>
        <div>ò</div>
        <div>ó</div>
        <div>ô</div>
        <div>õ</div>
        <div>ö</div>
        <div>÷</div>
        <div>ø</div>
        <div>ù</div>
        <div>ú</div>
        <div>û</div>
        <div>ü</div>
        <div>ý</div>
        <div>þ</div>
        <div>ÿ</div>
        <div>Ā</div>
        <div>ā</div>
        <div>Ă</div>
        <div>ă</div>
        <div>Ą</div>
        <div>ą</div>
        <div>Ć</div>
        <div>ć</div>
        <div>Ĉ</div>
        <div>ĉ</div>
        <div>Ċ</div>
        <div>ċ</div>
        <div>Č</div>
        <div>č</div>
        <div>Ď</div>
        <div>ď</div>
        <div>Đ</div>
        <div>đ</div>
        <div>Ē</div>
        <div>ē</div>
        <div>Ĕ</div>
        <div>ĕ</div>
        <div>Ė</div>
        <div>ė</div>
        <div>Ę</div>
        <div>ę</div>
        <div>Ě</div>
        <div>ě</div>
        <div>Ĝ</div>
        <div>ĝ</div>
        <div>Ğ</div>
        <div>ğ</div>
        <div>Ġ</div>
        <div>ġ</div>
        <div>Ģ</div>
        <div>ģ</div>
        <div>Ĥ</div>
        <div>ĥ</div>
        <div>Ħ</div>
        <div>ħ</div>
        <div>Ĩ</div>
        <div>ĩ</div>
        <div>Ī</div>
        <div>ī</div>
        <div>Ĭ</div>
        <div>ĭ</div>
        <div>Į</div>
        <div>į</div>
        <div>İ</div>
        <div>ı</div>
        <div>Ĳ</div>
        <div>ĳ</div>
        <div>Ĵ</div>
        <div>ĵ</div>
        <div>Ķ</div>
        <div>ķ</div>
        <div>ĸ</div>
        <div>Ĺ</div>
        <div>ĺ</div>
        <div>Ļ</div>
        <div>ļ</div>
        <div>Ľ</div>
        <div>ľ</div>
        <div>Ŀ</div>
        <div>ŀ</div>
        <div>Ł</div>
        <div>ł</div>
        <div>Ń</div>
        <div>ń</div>
        <div>Ņ</div>
        <div>ņ</div>
        <div>Ň</div>
        <div>ň</div>
        <div>ŉ</div>
        <div>Ŋ</div>
        <div>ŋ</div>
        <div>Ō</div>
        <div>ō</div>
        <div>Ŏ</div>
        <div>ŏ</div>
        <div>Ő</div>
        <div>ő</div>
        <div>Œ</div>
        <div>œ</div>
        <div>Ŕ</div>
        <div>ŕ</div>
        <div>Ŗ</div>
        <div>ŗ</div>
        <div>Ř</div>
        <div>ř</div>
        <div>Ś</div>
        <div>ś</div>
        <div>Ŝ</div>
        <div>ŝ</div>
        <div>Ş</div>
        <div>ş</div>
        <div>Š</div>
        <div>š</div>
        <div>Ţ</div>
        <div>ţ</div>
        <div>Ť</div>
        <div>ť</div>
        <div>Ŧ</div>
        <div>ŧ</div>
        <div>Ũ</div>
        <div>ũ</div>
        <div>Ū</div>
        <div>ū</div>
        <div>Ŭ</div>
        <div>ŭ</div>
        <div>Ů</div>
        <div>ů</div>
        <div>Ű</div>
        <div>ű</div>
        <div>Ų</div>
        <div>ų</div>
        <div>Ŵ</div>
        <div>ŵ</div>
        <div>Ŷ</div>
        <div>ŷ</div>
        <div>Ÿ</div>
        <div>Ź</div>
        <div>ź</div>
        <div>Ż</div>
        <div>ż</div>
        <div>Ž</div>
        <div>ž</div>
        <div>ſ</div>
        <div>ƒ</div>
        <div>Ǻ</div>
        <div>ǻ</div>
        <div>Ǽ</div>
        <div>ǽ</div>
        <div>Ǿ</div>
        <div>ǿ</div>
        <div>ˆ</div>
        <div>ˇ</div>
        <div>ˉ</div>
        <div>˘</div>
        <div>˙</div>
        <div>˚</div>
        <div>˛</div>
        <div>˜</div>
        <div>˝</div>
        <div>;</div>
        <div>΄</div>
        <div>΅</div>
        <div>Ά</div>
        <div>·</div>
        <div>Έ</div>
        <div>Ή</div>
        <div>Ί</div>
        <div>Ό</div>
        <div>Ύ</div>
        <div>Ώ</div>
        <div>ΐ</div>
        <div>Α</div>
        <div>Β</div>
        <div>Γ</div>
        <div>Δ</div>
        <div>Ε</div>
        <div>Ζ</div>
        <div>Η</div>
        <div>Θ</div>
        <div>Ι</div>
        <div>Κ</div>
        <div>Λ</div>
        <div>Μ</div>
        <div>Ν</div>
        <div>Ξ</div>
        <div>Ο</div>
        <div>Π</div>
        <div>Ρ</div>
        <div>Σ</div>
        <div>Τ</div>
        <div>Υ</div>
        <div>Φ</div>
        <div>Χ</div>
        <div>Ψ</div>
        <div>Ω</div>
        <div>Ϊ</div>
        <div>Ϋ</div>
        <div>ά</div>
        <div>έ</div>
        <div>ή</div>
        <div>ί</div>
        <div>ΰ</div>
        <div>α</div>
        <div>β</div>
        <div>γ</div>
        <div>δ</div>
        <div>ε</div>
        <div>ζ</div>
        <div>η</div>
        <div>θ</div>
        <div>ι</div>
        <div>κ</div>
        <div>λ</div>
        <div>μ</div>
        <div>ν</div>
        <div>ξ</div>
        <div>ο</div>
        <div>π</div>
        <div>ρ</div>
        <div>ς</div>
        <div>σ</div>
        <div>τ</div>
        <div>υ</div>
        <div>φ</div>
        <div>χ</div>
        <div>ψ</div>
        <div>ω</div>
        <div>ϊ</div>
        <div>ϋ</div>
        <div>ό</div>
        <div>ύ</div>
        <div>ώ</div>
        <div>Ѐ</div>
        <div>Ё</div>
        <div>Ђ</div>
        <div>Ѓ</div>
        <div>Є</div>
        <div>Ѕ</div>
        <div>І</div>
        <div>Ї</div>
        <div>Ј</div>
        <div>Љ</div>
        <div>Њ</div>
        <div>Ћ</div>
        <div>Ќ</div>
        <div>Ѝ</div>
        <div>Ў</div>
        <div>Џ</div>
        <div>А</div>
        <div>Б</div>
        <div>В</div>
        <div>Г</div>
        <div>Д</div>
        <div>Е</div>
        <div>Ж</div>
        <div>З</div>
        <div>И</div>
        <div>Й</div>
        <div>К</div>
        <div>Л</div>
        <div>М</div>
        <div>Н</div>
        <div>О</div>
        <div>П</div>
        <div>Р</div>
        <div>С</div>
        <div>Т</div>
        <div>У</div>
        <div>Ф</div>
        <div>Х</div>
        <div>Ц</div>
        <div>Ч</div>
        <div>Ш</div>
        <div>Щ</div>
        <div>Ъ</div>
        <div>Ы</div>
        <div>Ь</div>
        <div>Э</div>
        <div>Ю</div>
        <div>Я</div>
        <div>а</div>
        <div>б</div>
        <div>в</div>
        <div>г</div>
        <div>д</div>
        <div>е</div>
        <div>ж</div>
        <div>з</div>
        <div>и</div>
        <div>й</div>
        <div>к</div>
        <div>л</div>
        <div>м</div>
        <div>н</div>
        <div>о</div>
        <div>п</div>
        <div>р</div>
        <div>с</div>
        <div>т</div>
        <div>у</div>
        <div>ф</div>
        <div>х</div>
        <div>ц</div>
        <div>ч</div>
        <div>ш</div>
        <div>щ</div>
        <div>ъ</div>
        <div>ы</div>
        <div>ь</div>
        <div>э</div>
        <div>ю</div>
        <div>я</div>
        <div>ѐ</div>
        <div>ё</div>
        <div>ђ</div>
        <div>ѓ</div>
        <div>є</div>
        <div>ѕ</div>
        <div>і</div>
        <div>ї</div>
        <div>ј</div>
        <div>љ</div>
        <div>њ</div>
        <div>ћ</div>
        <div>ќ</div>
        <div>ѝ</div>
        <div>ў</div>
        <div>џ</div>
        <div>Ґ</div>
        <div>ґ</div>
        <div>Ẁ</div>
        <div>ẁ</div>
        <div>Ẃ</div>
        <div>ẃ</div>
        <div>Ẅ</div>
        <div>ẅ</div>
        <div>Ỳ</div>
        <div>ỳ</div>
        <div>–</div>
        <div>—</div>
        <div>―</div>
        <div>‗</div>
        <div>‘</div>
        <div>’</div>
        <div>‚</div>
        <div>‛</div>
        <div>“</div>
        <div>”</div>
        <div>„</div>
        <div>†</div>
        <div>‡</div>
        <div>•</div>
        <div>…</div>
        <div>‰</div>
        <div>′</div>
        <div>″</div>
        <div>‹</div>
        <div>›</div>
        <div>‼</div>
        <div>‾</div>
        <div>⁄</div>
        <div>ⁿ</div>
        <div>₣</div>
        <div>₤</div>
        <div>₧</div>
        <div>€</div>
        <div>℅</div>
        <div>ℓ</div>
        <div>№</div>
        <div>™</div>
        <div>Ω</div>
        <div>℮</div>
        <div>⅛</div>
        <div>⅜</div>
        <div>⅝</div>
        <div>⅞</div>
        <div>←</div>
        <div>↑</div>
        <div>→</div>
        <div>↓</div>
        <div>↔</div>
        <div>↕</div>
        <div>↨</div>
        <div>∂</div>
        <div>∆</div>
        <div>∏</div>
        <div>∑</div>
        <div>−</div>
        <div>∕</div>
        <div>∙</div>
        <div>√</div>
        <div>∞</div>
        <div>∟</div>
        <div>∩</div>
        <div>∫</div>
        <div>≈</div>
        <div>≠</div>
        <div>≡</div>
        <div>≤</div>
        <div>≥</div>
        <div>⌂</div>
        <div>⌐</div>
        <div>⌠</div>
        <div>⌡</div>
        <div>─</div>
        <div>│</div>
        <div>┌</div>
        <div>┐</div>
        <div>└</div>
        <div>┘</div>
        <div>├</div>
        <div>┤</div>
        <div>┬</div>
        <div>┴</div>
        <div>┼</div>
        <div>═</div>
        <div>║</div>
        <div>╒</div>
        <div>╓</div>
        <div>╔</div>
        <div>╕</div>
        <div>╖</div>
        <div>╗</div>
        <div>╘</div>
        <div>╙</div>
        <div>╚</div>
        <div>╛</div>
        <div>╜</div>
        <div>╝</div>
        <div>╞</div>
        <div>╟</div>
        <div>╠</div>
        <div>╡</div>
        <div>╢</div>
        <div>╣</div>
        <div>╤</div>
        <div>╥</div>
        <div>╦</div>
        <div>╧</div>
        <div>╨</div>
        <div>╩</div>
        <div>╪</div>
        <div>╫</div>
        <div>╬</div>
        <div>▀</div>
        <div>▄</div>
        <div>█</div>
        <div>▌</div>
        <div>▐</div>
        <div>░</div>
        <div>▒</div>
        <div>▓</div>
        <div>■</div>
        <div>□</div>
        <div>▪</div>
        <div>▫</div>
        <div>▬</div>
        <div>▲</div>
        <div>►</div>
        <div>▼</div>
        <div>◄</div>
        <div>◊</div>
        <div>○</div>
        <div>●</div>
        <div>◘</div>
        <div>◙</div>
        <div>◦</div>
        <div>☺</div>
        <div>☻</div>
        <div>☼</div>
        <div>♀</div>
        <div>♂</div>
        <div>♠</div>
        <div>♣</div>
        <div>♥</div>
        <div>♦</div>
        <div>♪</div>
        <div>♫</div>
        <div></div>
        <div></div>
        <div>ﬁ</div>
        <div>ﬂ</div>
    </div>
  </div>
</template>

<style scoped>

.typeColumn {
  flex: 1;
}

.typeColumn .charmap {
  padding: 0 1rem;
  box-shadow: 1px 0px 0px var(--accent-color);
}

.typeColumn:last-of-type .charmap {
  margin-right: 0;
  box-shadow: none;
}

.typeColumn .charmap {
  display: flex;
  flex-flow: row wrap;
  justify-content: space-around;
  align-content: flex-start;
}

.typeColumn .charmap div {
  line-height: 1.5;
  letter-spacing: 0;
  font-size: var(--column-font-size);
  font-weight: var(--font-weight);
  font-style: var(--font-style);
  width: calc(1.5 * var(--column-font-size));
  align-self: center;
  text-align: center;
  border: .1rem solid var(--background-color);
}

.typeColumn .charmap div:hover, .typeColumn .charmap div:focus {
  border: .1rem solid var(--text-color);
}

.typeColumn h2 {
  font-style: normal;
  line-height: 1;
  border-bottom: .1rem solid var(--accent-color);
  margin: 0 1rem 1rem 1rem;
  font-weight: normal;
  height: 3rem;
  /*Tries to break on word, then letter*/
  word-break: break-word;
  overflow-y: hidden;
}
</style>

<script>
export default {
  name: 'Typeface',
  props: [
    'typeface',
  ],
  data() {
    return {};
  },
};
</script>
